# Generated by Django 6.0.5 on 2026-05-27 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chembl_id', models.CharField(blank=True, max_length=20)),
                ('pubchem_cid', models.IntegerField(blank=True, null=True)),
                ('smiles', models.TextField(blank=True)),
                ('inchi_key', models.CharField(blank=True, max_length=27)),
                ('molecular_formula', models.CharField(blank=True, max_length=100)),
                ('molecular_weight', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phase', models.CharField(choices=[('preclinical', 'Preclinical'), ('phase1', 'Phase 1'), ('phase2', 'Phase 2'), ('phase3', 'Phase 3')], default='preclinical', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='CompoundProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('physicochemical', 'Physicochemical'), ('admet', 'ADMET'), ('toxicity', 'Toxicity')], max_length=30)),
                ('source', models.CharField(choices=[('pubchem', 'PubChem'), ('pkcsm', 'pkCSM'), ('comptox', 'EPA CompTox'), ('chembl', 'ChEMBL')], max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='core.compound')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('experiment_type', models.CharField(choices=[('formulation', 'Formulation'), ('synthesis', 'Synthesis'), ('analytical', 'Analytical'), ('stability', 'Stability')], max_length=30)),
                ('objective', models.TextField()),
                ('variables', models.JSONField(default=list)),
                ('success_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='core.compound')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(default=dict)),
                ('interpretation', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('optimize', 'Optimize'), ('reproduce', 'Reproduce'), ('scale', 'Scale Up'), ('abort', 'Abort')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('pubchem', 'PubChem'), ('chembl', 'ChEMBL'), ('opentargets', 'Open Targets'), ('uniprot', 'UniProt'), ('pkcsm', 'pkCSM'), ('comptox', 'EPA CompTox'), ('pubmed', 'PubMed'), ('clinicaltrials', 'ClinicalTrials.gov'), ('openfda', 'OpenFDA'), ('dailymed', 'DailyMed'), ('askcos', 'ASKCOS'), ('nist', 'NIST WebBook'), ('openfda_guidance', 'OpenFDA Guidance')], max_length=30)),
                ('query_key', models.CharField(db_index=True, max_length=512)),
                ('response_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'unique_together': {('source', 'query_key')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('process_summary', 'Process Summary'), ('risk_report', 'Risk Report'), ('handoff', 'Handoff Note')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='compound',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='core.project'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.project'),
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_factors', models.JSONField(default=list)),
                ('risk_heat_map', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='core.project')),
            ],
        ),
    ]
