# Generated by Django 6.0.5 on 2026-05-27 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInvestigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chembl_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('smiles', models.TextField(blank=True)),
                ('disease_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('process_summary', 'Process Summary'), ('risk_report', 'Risk Report'), ('handoff', 'Handoff Note'), ('analog_report', 'Analog Development Report')], max_length=30),
        ),
        migrations.AlterField(
            model_name='externaldatacache',
            name='source',
            field=models.CharField(choices=[('pubchem', 'PubChem'), ('chembl', 'ChEMBL'), ('opentargets', 'Open Targets'), ('uniprot', 'UniProt'), ('pkcsm', 'pkCSM'), ('comptox', 'EPA CompTox'), ('pubmed', 'PubMed'), ('clinicaltrials', 'ClinicalTrials.gov'), ('openfda', 'OpenFDA'), ('dailymed', 'DailyMed'), ('askcos', 'ASKCOS'), ('nist', 'NIST WebBook'), ('openfda_guidance', 'OpenFDA Guidance'), ('surechembl', 'SureChEMBL'), ('espacenet', 'Espacenet')], max_length=30),
        ),
        migrations.CreateModel(
            name='AnalogCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.TextField()),
                ('pubchem_cid', models.IntegerField(blank=True, null=True)),
                ('chembl_id', models.CharField(blank=True, max_length=20)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('patent_status', models.CharField(choices=[('free', 'Free to Operate'), ('covered', 'Patent Covered'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('patent_refs', models.JSONField(default=list)),
                ('admet_data', models.JSONField(default=dict)),
                ('shortlisted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.druginvestigation')),
            ],
        ),
    ]
