# Generated by Django 6.0.5 on 2026-05-27 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_druginvestigation_alter_document_doc_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogcandidate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analog_candidates', to='core.project'),
        ),
        migrations.AddField(
            model_name='druginvestigation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='core.project'),
        ),
        migrations.CreateModel(
            name='SynthesisPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_smiles', models.TextField()),
                ('plan_type', models.CharField(choices=[('retro', 'Single-Step Retro'), ('tree', 'Multi-Step Tree')], default='retro', max_length=10)),
                ('route_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthesis_plans', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='synthesis_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='core.synthesisplan'),
        ),
    ]
