# Generated by Django 6.0.5 on 2026-06-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_excipient_targetprofile_project_pathway_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogcandidate',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
